import {useEffect,useState} from 'react'
import {AudioLines,BookOpen,CheckCircle2,ExternalLink,Info,KeyRound,LockKeyhole,Server,ShieldCheck,Wifi,WifiOff} from 'lucide-react'
import {fetchHealth} from '../api'
export default function Settings(){
  const [health,setHealth]=useState<Awaited<ReturnType<typeof fetchHealth>>>(null)
  const [checked,setChecked]=useState(false)
  const refresh=async()=>{setHealth(await fetchHealth());setChecked(true)}
  useEffect(()=>{void refresh()},[])
  return <div className="page-content settings-page"><div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-dot"/> ABOUT YOUR WORKSPACE</div><h1>Make it yours<span className="heading-period">.</span></h1><p>Connection health, API configuration and demo constraints.</p></div></div>
    <div className="settings-grid"><section className="settings-card"><div className="settings-icon"><Server size={24}/></div><h2>Backend connection</h2><p>The interface runs in demo mode without FastAPI. For microphone streaming, run the backend with an OpenAI API key.</p><div className="settings-state">{health?<Wifi size={17}/>:<WifiOff size={17}/>}<strong>{health?'Backend connected':'Backend not detected'}</strong><span>{health?'localhost:8000':'Demo mode is available'}</span></div><button className="secondary-button" onClick={()=>void refresh()}>{checked?'Check again':'Check connection'}</button></section>
      <section className="settings-card"><div className="settings-icon green"><KeyRound size={24}/></div><h2>API configuration</h2><p>Put your OpenAI key in <code>backend/.env</code>, never in your React source. Restart the backend after editing it.</p><div className="settings-state"><span className={`small-dot ${health?.live_configured?'green':'amber'}`}/><strong>{health?.live_configured?'Configured':'Not configured'}</strong><span>{health?.transcription_model||'gpt-live-transcribe'}</span></div><span className="muted-inline"><LockKeyhole size={14}/> Your key remains server-side.</span></section>
      <section className="settings-card"><div className="settings-icon blue"><AudioLines size={24}/></div><h2>Realtime pipeline</h2><p>Speech is captured as 24 kHz PCM, sent through a server-side realtime transcription connection and surfaced as partial and final captions.</p><div className="settings-list"><span><CheckCircle2 size={16}/> Separate animation queue</span><span><CheckCircle2 size={16}/> Exportable English transcript</span><span><CheckCircle2 size={16}/> Catalog-only fallback</span></div></section>
      <section className="settings-card"><div className="settings-icon orange"><BookOpen size={24}/></div><h2>ASL validation</h2><p>The bundled animations are procedural illustrations, not authentic ASL. The tutor checks simple finger configurations only.</p><div className="settings-list"><span><Info size={16}/> All starter clips are marked unverified</span><span><Info size={16}/> Unknown content falls back to captions</span><span><Info size={16}/> Qualified review required before real use</span></div></section></div>
    <div className="settings-footer"><ShieldCheck size={22}/><div><strong>Designed as a learning and accessibility research prototype.</strong><p>Sign does not replace professional interpretation, and its automated feedback cannot establish ASL fluency. Get permission before recording classes or speeches. This prototype does not store audio or webcam footage; audio sent to OpenAI is subject to the provider’s retention policies.</p></div><a href="https://developers.openai.com/api/docs/guides/realtime-transcription" target="_blank" rel="noreferrer">API docs <ExternalLink size={14}/></a></div>
  </div>
}
