import type { LearningItem, Lesson } from './types'

export const LEARNING_ITEMS: LearningItem[] = [
  {id:'open',lessonId:'foundations',name:'Open hand',description:'Build control for signs that use a flat or open hand.',animationId:'hello',instructions:['Keep the whole hand in frame','Extend all four fingers comfortably','Hold the shape for 12 matching frames'],components:{handshape:'Four fingers extended',focus:'Comfortably straight fingers'},practice:{enabled:true,mode:'handshape',targetHandState:'open',scopeLabel:'Foundational handshape'},validationStatus:'illustrative'},
  {id:'fist',lessonId:'foundations',name:'Closed hand',description:'Practice a relaxed closed hand without excess tension.',animationId:'yes',instructions:['Keep your wrist visible','Curl all four fingers gently','Hold the shape for 12 matching frames'],components:{handshape:'Four fingers curled',focus:'Relaxed, even curl'},practice:{enabled:true,mode:'handshape',targetHandState:'fist',scopeLabel:'Foundational handshape'},validationStatus:'illustrative'},
  {id:'index',lessonId:'foundations',name:'Index extension',description:'Isolate the index finger while the other fingers remain curled.',animationId:'question',instructions:['Extend your index finger','Curl the middle, ring and little fingers','Hold the shape steadily'],components:{handshape:'Index finger extended',focus:'Independent finger control'},practice:{enabled:true,mode:'handshape',targetHandState:'index',scopeLabel:'Foundational handshape'},validationStatus:'illustrative'},
  {id:'two-open',lessonId:'foundations',name:'Two-hand coordination',description:'Keep two open handshapes visible at the same time.',animationId:'learn',instructions:['Fit both hands in frame','Extend all four fingers on each hand','Hold both shapes together'],components:{handshape:'Two open hands',focus:'Symmetry and visibility'},practice:{enabled:true,mode:'handshape',targetHandState:'two-open',scopeLabel:'Foundational handshape'},validationStatus:'illustrative'},

  {id:'hello',lessonId:'greetings',name:'Hello',description:'A common greeting used to begin a conversation.',animationId:'hello',instructions:['Study the avatar motion','Practice the open handshape','Movement and position are not scored yet'],components:{handshape:'Open hand',position:'Near the forehead',movement:'Move outward',orientation:'Palm facing outward'},practice:{enabled:true,mode:'handshape',targetHandState:'open',scopeLabel:'HELLO handshape only'},validationStatus:'unverified'},
  {id:'thank_you',lessonId:'greetings',name:'Thank you',description:'A polite expression of appreciation.',animationId:'thank_you',instructions:['Watch where the motion begins','Practice a comfortably open hand','Only the handshape is measured'],components:{handshape:'Open hand',position:'Near the chin',movement:'Move outward',orientation:'Palm angled toward the face'},practice:{enabled:true,mode:'handshape',targetHandState:'open',scopeLabel:'THANK YOU handshape only'},validationStatus:'unverified'},
  {id:'please',lessonId:'greetings',name:'Please',description:'A polite expression used when making a request.',animationId:'please',instructions:['Observe the circular reference motion','Practice a flat open hand','Position and movement are not scored'],components:{handshape:'Flat open hand',position:'At the chest',movement:'Small circular motion',orientation:'Palm toward the body'},practice:{enabled:true,mode:'handshape',targetHandState:'open',scopeLabel:'PLEASE handshape only'},validationStatus:'unverified'},

  {id:'name',lessonId:'introductions',name:'Name',description:'Used when sharing or asking for a name.',animationId:'name',instructions:['Watch the two-hand reference','Notice the repeated contact','Full practice needs two-hand orientation analysis'],components:{handshape:'Two H-like handshapes',position:'In front of the body',movement:'Repeated contact'},practice:{enabled:false,mode:'demo-only',scopeLabel:'Demonstration only'},validationStatus:'unverified'},
  {id:'me',lessonId:'introductions',name:'Me',description:'Points to the signer as a participant.',animationId:'me',instructions:['Study the pointing motion','Practice isolating the index finger','Position is not scored'],components:{handshape:'Index finger extended',position:'Toward the chest',movement:'Short inward point'},practice:{enabled:true,mode:'handshape',targetHandState:'index',scopeLabel:'ME handshape only'},validationStatus:'unverified'},
  {id:'you',lessonId:'introductions',name:'You',description:'Points toward the person being addressed.',animationId:'you',instructions:['Study the direction of the reference','Practice isolating the index finger','Direction is not scored'],components:{handshape:'Index finger extended',position:'In neutral signing space',movement:'Point outward'},practice:{enabled:true,mode:'handshape',targetHandState:'index',scopeLabel:'YOU handshape only'},validationStatus:'unverified'},

  {id:'help',lessonId:'classroom',name:'Help',description:'A useful classroom request for assistance.',animationId:'help',instructions:['Observe both hands in the reference','Notice how the hands work together','Mixed two-hand analysis is not available yet'],components:{handshape:'Closed dominant hand over open support hand',position:'In front of the torso',movement:'Move upward together'},practice:{enabled:false,mode:'demo-only',scopeLabel:'Demonstration only'},validationStatus:'unverified'},
  {id:'again',lessonId:'classroom',name:'Again',description:'Requests repetition or indicates another occurrence.',animationId:'again',instructions:['Watch the curved movement','Notice the two different hand roles','Movement analysis is coming later'],components:{handshape:'Two different handshapes',position:'In front of the body',movement:'Curved movement toward the support hand'},practice:{enabled:false,mode:'demo-only',scopeLabel:'Demonstration only'},validationStatus:'unverified'},
  {id:'understand',lessonId:'classroom',name:'Understand',description:'Expresses comprehension in a classroom exchange.',animationId:'understand',instructions:['Watch the finger change in the reference','Practice the final index extension','The change over time is not scored'],components:{handshape:'Index finger extended at the end',position:'Near the forehead',movement:'Index finger opens upward'},practice:{enabled:true,mode:'handshape',targetHandState:'index',scopeLabel:'UNDERSTAND final handshape only'},validationStatus:'unverified'},
  {id:'question',lessonId:'classroom',name:'Question',description:'Introduces or refers to a question.',animationId:'question',instructions:['Study the reference trajectory','Practice the index handshape','The movement path is not scored'],components:{handshape:'Index finger extended',position:'In neutral signing space',movement:'Draw the reference path'},practice:{enabled:true,mode:'handshape',targetHandState:'index',scopeLabel:'QUESTION handshape only'},validationStatus:'unverified'},
]

export const LESSONS: Lesson[] = [
  {id:'foundations',title:'Foundations',subtitle:'Warm-up handshapes',items:['open','fist','index','two-open']},
  {id:'greetings',title:'Greetings',subtitle:'Lesson 1',items:['hello','thank_you','please']},
  {id:'introductions',title:'Introductions',subtitle:'Lesson 2',items:['name','me','you']},
  {id:'classroom',title:'Classroom Basics',subtitle:'Lesson 3',items:['help','again','understand','question']},
]

export const learningItem = (id:string) => LEARNING_ITEMS.find(item=>item.id===id) ?? LEARNING_ITEMS[0]
